// Generated by generate_groups.py, do not edit by hand.
export type TeamCandidate = {
  id: number
  teamA: string[]
  teamB: string[]
}

export const CANDIDATES: TeamCandidate[] = [
  { id: 0, teamA: ["Lucas", "Jonathan", "Elias", "Jonas"], teamB: ["Oscar", "Viktor", "Nikolaj", "Christoffer"] },
  { id: 1, teamA: ["Jonathan", "Elias", "Oscar", "Nikolaj"], teamB: ["Lucas", "Viktor", "Christoffer", "Jonas"] },
  { id: 2, teamA: ["Lucas", "Jonathan", "Viktor", "Christoffer"], teamB: ["Elias", "Oscar", "Nikolaj", "Jonas"] },
  { id: 3, teamA: ["Lucas", "Elias", "Oscar", "Nikolaj"], teamB: ["Jonathan", "Viktor", "Christoffer", "Jonas"] },
  { id: 4, teamA: ["Jonathan", "Oscar", "Viktor", "Nikolaj"], teamB: ["Lucas", "Elias", "Christoffer", "Jonas"] },
  { id: 5, teamA: ["Lucas", "Elias", "Viktor", "Jonas"], teamB: ["Jonathan", "Oscar", "Nikolaj", "Christoffer"] },
  { id: 6, teamA: ["Jonathan", "Elias", "Viktor", "Christoffer"], teamB: ["Lucas", "Oscar", "Nikolaj", "Jonas"] },
  { id: 7, teamA: ["Elias", "Oscar", "Viktor", "Nikolaj"], teamB: ["Lucas", "Jonathan", "Jonas", "Christoffer"] },
  { id: 8, teamA: ["Lucas", "Oscar", "Viktor", "Nikolaj"], teamB: ["Jonathan", "Elias", "Christoffer", "Jonas"] },
  { id: 9, teamA: ["Lucas", "Jonathan", "Oscar", "Nikolaj"], teamB: ["Elias", "Viktor", "Jonas", "Christoffer"] },
]
