// Generated by generate_groups.py, do not edit by hand.
export type TeamCandidate = {
  id: number
  teamA: string[]
  teamB: string[]
}

export const CANDIDATES: TeamCandidate[] = [
  { id: 0, teamA: ["Oscar", "Nikolaj", "Lucas", "Jonathan"], teamB: ["Elias", "Viktor", "Jonas", "Christoffer"] },
  { id: 1, teamA: ["Oscar", "Nikolaj", "Lucas", "Elias"], teamB: ["Jonathan", "Viktor", "Jonas", "Christoffer"] },
  { id: 2, teamA: ["Oscar", "Nikolaj", "Lucas", "Viktor"], teamB: ["Jonathan", "Elias", "Jonas", "Christoffer"] },
  { id: 3, teamA: ["Oscar", "Nikolaj", "Lucas", "Jonas"], teamB: ["Jonathan", "Elias", "Viktor", "Christoffer"] },
  { id: 4, teamA: ["Oscar", "Nikolaj", "Lucas", "Christoffer"], teamB: ["Jonathan", "Elias", "Viktor", "Jonas"] },
  { id: 5, teamA: ["Oscar", "Nikolaj", "Jonathan", "Elias"], teamB: ["Lucas", "Viktor", "Jonas", "Christoffer"] },
  { id: 6, teamA: ["Oscar", "Nikolaj", "Jonathan", "Viktor"], teamB: ["Lucas", "Elias", "Jonas", "Christoffer"] },
  { id: 7, teamA: ["Oscar", "Nikolaj", "Jonathan", "Jonas"], teamB: ["Lucas", "Elias", "Viktor", "Christoffer"] },
  { id: 8, teamA: ["Oscar", "Nikolaj", "Jonathan", "Christoffer"], teamB: ["Lucas", "Elias", "Viktor", "Jonas"] },
  { id: 9, teamA: ["Oscar", "Nikolaj", "Elias", "Viktor"], teamB: ["Lucas", "Jonathan", "Jonas", "Christoffer"] },
  { id: 10, teamA: ["Oscar", "Nikolaj", "Elias", "Jonas"], teamB: ["Lucas", "Jonathan", "Viktor", "Christoffer"] },
  { id: 11, teamA: ["Oscar", "Nikolaj", "Elias", "Christoffer"], teamB: ["Lucas", "Jonathan", "Viktor", "Jonas"] },
  { id: 12, teamA: ["Oscar", "Nikolaj", "Viktor", "Jonas"], teamB: ["Lucas", "Jonathan", "Elias", "Christoffer"] },
  { id: 13, teamA: ["Oscar", "Nikolaj", "Viktor", "Christoffer"], teamB: ["Lucas", "Jonathan", "Elias", "Jonas"] },
]
