// Generated by generate_groups.py, do not edit by hand.
export type TeamCandidate = {
  id: number
  teamA: string[]
  teamB: string[]
}

export const CANDIDATES: TeamCandidate[] = [
  { id: 0, teamA: ["Lucas", "Jonathan", "Elias", "Jonas"], teamB: ["Oscar", "Viktor", "Christoffer", "Nikolaj"] },
  { id: 1, teamA: ["Lucas", "Jonathan", "Elias", "Christoffer"], teamB: ["Oscar", "Viktor", "Jonas", "Nikolaj"] },
  { id: 2, teamA: ["Lucas", "Jonathan", "Elias", "Nikolaj"], teamB: ["Oscar", "Viktor", "Jonas", "Christoffer"] },
  { id: 3, teamA: ["Lucas", "Jonathan", "Oscar", "Jonas"], teamB: ["Elias", "Viktor", "Christoffer", "Nikolaj"] },
  { id: 4, teamA: ["Lucas", "Jonathan", "Oscar", "Christoffer"], teamB: ["Elias", "Viktor", "Jonas", "Nikolaj"] },
  { id: 5, teamA: ["Lucas", "Jonathan", "Oscar", "Nikolaj"], teamB: ["Elias", "Viktor", "Jonas", "Christoffer"] },
  { id: 6, teamA: ["Lucas", "Jonathan", "Viktor", "Jonas"], teamB: ["Elias", "Oscar", "Christoffer", "Nikolaj"] },
  { id: 7, teamA: ["Lucas", "Jonathan", "Viktor", "Christoffer"], teamB: ["Elias", "Oscar", "Jonas", "Nikolaj"] },
  { id: 8, teamA: ["Lucas", "Jonathan", "Viktor", "Nikolaj"], teamB: ["Elias", "Oscar", "Jonas", "Christoffer"] },
  { id: 9, teamA: ["Lucas", "Jonathan", "Jonas", "Christoffer"], teamB: ["Elias", "Oscar", "Viktor", "Nikolaj"] },
  { id: 10, teamA: ["Lucas", "Jonathan", "Jonas", "Nikolaj"], teamB: ["Elias", "Oscar", "Viktor", "Christoffer"] },
  { id: 11, teamA: ["Lucas", "Jonathan", "Christoffer", "Nikolaj"], teamB: ["Elias", "Oscar", "Viktor", "Jonas"] },
  { id: 12, teamA: ["Lucas", "Elias", "Oscar", "Jonas"], teamB: ["Jonathan", "Viktor", "Christoffer", "Nikolaj"] },
  { id: 13, teamA: ["Lucas", "Elias", "Oscar", "Christoffer"], teamB: ["Jonathan", "Viktor", "Jonas", "Nikolaj"] },
  { id: 14, teamA: ["Lucas", "Elias", "Oscar", "Nikolaj"], teamB: ["Jonathan", "Viktor", "Jonas", "Christoffer"] },
  { id: 15, teamA: ["Lucas", "Elias", "Viktor", "Jonas"], teamB: ["Jonathan", "Oscar", "Christoffer", "Nikolaj"] },
  { id: 16, teamA: ["Lucas", "Elias", "Viktor", "Christoffer"], teamB: ["Jonathan", "Oscar", "Jonas", "Nikolaj"] },
  { id: 17, teamA: ["Lucas", "Elias", "Viktor", "Nikolaj"], teamB: ["Jonathan", "Oscar", "Jonas", "Christoffer"] },
  { id: 18, teamA: ["Lucas", "Elias", "Jonas", "Christoffer"], teamB: ["Jonathan", "Oscar", "Viktor", "Nikolaj"] },
  { id: 19, teamA: ["Lucas", "Elias", "Jonas", "Nikolaj"], teamB: ["Jonathan", "Oscar", "Viktor", "Christoffer"] },
  { id: 20, teamA: ["Lucas", "Elias", "Christoffer", "Nikolaj"], teamB: ["Jonathan", "Oscar", "Viktor", "Jonas"] },
  { id: 21, teamA: ["Lucas", "Oscar", "Viktor", "Jonas"], teamB: ["Jonathan", "Elias", "Christoffer", "Nikolaj"] },
  { id: 22, teamA: ["Lucas", "Oscar", "Viktor", "Christoffer"], teamB: ["Jonathan", "Elias", "Jonas", "Nikolaj"] },
  { id: 23, teamA: ["Lucas", "Oscar", "Viktor", "Nikolaj"], teamB: ["Jonathan", "Elias", "Jonas", "Christoffer"] },
  { id: 24, teamA: ["Lucas", "Oscar", "Jonas", "Christoffer"], teamB: ["Jonathan", "Elias", "Viktor", "Nikolaj"] },
  { id: 25, teamA: ["Lucas", "Oscar", "Jonas", "Nikolaj"], teamB: ["Jonathan", "Elias", "Viktor", "Christoffer"] },
  { id: 26, teamA: ["Lucas", "Oscar", "Christoffer", "Nikolaj"], teamB: ["Jonathan", "Elias", "Viktor", "Jonas"] },
  { id: 27, teamA: ["Lucas", "Viktor", "Jonas", "Christoffer"], teamB: ["Jonathan", "Elias", "Oscar", "Nikolaj"] },
  { id: 28, teamA: ["Lucas", "Viktor", "Jonas", "Nikolaj"], teamB: ["Jonathan", "Elias", "Oscar", "Christoffer"] },
  { id: 29, teamA: ["Lucas", "Viktor", "Christoffer", "Nikolaj"], teamB: ["Jonathan", "Elias", "Oscar", "Jonas"] },
]
